import Link from "next/link";
import { ArrowUpRight, CalendarDays, Instagram, MapPin, MessageCircle } from "lucide-react";
import { EventGrid } from "@/components/EventGrid";
import { MobileMenu } from "@/components/MobileMenu";

export default function Home(){return <main>
<header className="nav"><Link href="/" className="brand" aria-label="Jalene Decor & Event"><img src="/jalene-logo.svg" alt="Jalene Decor & Event" className="brand-logo"/></Link><nav className="desktop-nav"><a href="#events">Events</a><a href="#services">Services</a><a href="#story">Our story</a><a href="#contact">Contact</a></nav><a className="nav-cta" href="#contact">Plan an event <ArrowUpRight size={16}/></a><MobileMenu/></header>
<section className="hero"><div className="hero-image"/><div className="hero-overlay"/><div className="hero-topline"><span>ADDIS ABABA · ETHIOPIA</span><span className="hero-dot"/><span>EVENTS / EXPERIENCES / PRODUCTION</span></div><div className="hero-content"><p className="eyebrow">Independent event house · Ethiopia</p><h1>Make the<br/><em>moment</em> matter.</h1><p className="hero-copy">Jalene turns ideas into beautifully produced experiences — from intimate celebrations to high-energy nights and cultural moments.</p><div className="hero-actions"><a className="button button-light" href="#events">Explore events <ArrowUpRight size={17}/></a><a className="text-link" href="#contact">Work with Jalene <span>→</span></a></div></div><div className="hero-scroll">SCROLL TO DISCOVER <span>↓</span></div></section>
<section className="intro section"><div className="section-kicker"><span>01</span><span>THE HOUSE</span></div><div className="intro-grid"><h2>We don&apos;t just<br/><span>run events.</span><br/>We create memories.</h2><div><p className="lead">Jalene Event is an Ethiopian creative event house built around one simple idea: the best events should feel effortless, distinctive and impossible to forget.</p><p>We bring together creative direction, planning, production and guest experience under one roof. The result is an event that has a point of view — not just a schedule.</p><a className="arrow-link" href="#services">Discover what we do <ArrowUpRight size={17}/></a></div></div></section>
<section id="events" className="events section"><div className="section-head"><div className="section-kicker"><span>02</span><span>WHAT&apos;S HAPPENING</span></div><Link href="/events" className="arrow-link">View all events <ArrowUpRight size={17}/></Link></div><div className="events-title-row"><h2>Upcoming<br/><em>experiences.</em></h2><p>Discover selected experiences taking place across Addis Ababa and beyond.</p></div><EventGrid/></section>
<section id="services" className="services section dark"><div className="section-kicker light"><span>03</span><span>WHAT WE DO</span></div><div className="services-head"><h2>From first idea<br/>to <em>final applause.</em></h2><p>Strategy, creative and production working as one team.</p></div><div className="service-list">{[["01","Event Strategy","Concept development, event architecture, audience journey and run-of-show."],["02","Creative Direction","Visual identity, stage direction, content, atmosphere and brand moments."],["03","Production","Venue, technical production, suppliers, staffing, logistics and show calling."],["04","Private Experiences","Weddings, birthdays, launches, dinners and intimate celebrations designed around you."]].map(([n,title,body])=><div className="service-row" key={n}><span className="service-no">{n}</span><h3>{title}</h3><p>{body}</p><ArrowUpRight className="service-arrow" size={21}/></div>)}</div></section>
<section id="story" className="story section"><div className="story-image"/><div className="story-copy"><div className="section-kicker"><span>04</span><span>OUR STORY</span></div><h2>Rooted in<br/><em>Ethiopia.</em><br/>Open to the world.</h2><p>Our work is inspired by Ethiopia&apos;s people, rhythm, hospitality and creative energy. We build contemporary experiences that feel local without feeling limited.</p><div className="story-facts"><div><strong>01</strong><span>Creative<br/>direction</span></div><div><strong>02</strong><span>End-to-end<br/>production</span></div><div><strong>03</strong><span>Human-first<br/>experience</span></div></div></div></section>
<section className="marquee"><div>JALENE EVENT <span>✦</span> ADDIS ABABA <span>✦</span> ETHIOPIA <span>✦</span> CREATE THE MOMENT <span>✦</span> JALENE EVENT <span>✦</span></div></section>
<section id="contact" className="contact section"><div className="section-kicker"><span>05</span><span>START SOMETHING</span></div><div className="contact-grid"><div><h2>Have a moment<br/>worth <em>creating?</em></h2><p>Tell us what you&apos;re planning. We&apos;ll come back with the right next step.</p></div><form className="contact-form" action="mailto:hello@jaleneevent.com" method="post" encType="text/plain"><label>Name<input name="name" required placeholder="Your name"/></label><label>Email<input name="email" type="email" required placeholder="you@example.com"/></label><label>Event type<select name="event"><option>Corporate event</option><option>Concert / entertainment</option><option>Wedding / private</option><option>Brand activation</option><option>Other</option></select></label><label>Tell us about it<textarea name="message" rows={4} placeholder="Date, location, guest count, idea..."/></label><button className="button button-dark" type="submit">Send inquiry <ArrowUpRight size={17}/></button><small>Replace the email address with Jalene&apos;s official inbox before launch.</small></form></div></section>
<footer className="footer"><div className="footer-top"><div><div className="footer-brand">JALENE<span>DECOR &amp; EVENT</span></div><p>Create the moment.<br/>Remember the experience.</p></div><div className="footer-links"><a href="#events">Events</a><a href="#services">Services</a><a href="#story">Our story</a><a href="#contact">Contact</a></div><div className="footer-social"><a href="#" aria-label="Instagram"><Instagram size={20}/></a><a href="#" aria-label="WhatsApp"><MessageCircle size={20}/></a></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Jalene Event. Ethiopia.</span><span>Independent event house.</span></div></footer>
</main>}