import Link from "next/link";
import { ArrowLeft, ArrowUpRight, CalendarDays, MapPin } from "lucide-react";
import { notFound } from "next/navigation";

const data:Record<string,{title:string;date:string;category:string;place:string;image:string;desc:string}>={
 "jalene-after-dark":{title:"Jalene After Dark",date:"18 OCT 2026",category:"NIGHTLIFE",place:"Addis Ababa, Ethiopia",image:"https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=2200&q=90",desc:"A late-night Jalene experience built around music, movement, light and the electric energy of Addis."},
 "golden-hour":{title:"Golden Hour",date:"07 NOV 2026",category:"EXPERIENCE",place:"Addis Ababa, Ethiopia",image:"https://images.unsplash.com/photo-1507504031003-b417219a0fde?auto=format&fit=crop&w=2200&q=90",desc:"An intimate golden-hour gathering designed for conversation, atmosphere and a beautiful start to the night."},
 "the-gathering":{title:"The Gathering",date:"21 NOV 2026",category:"CULTURE",place:"Addis Ababa, Ethiopia",image:"https://images.unsplash.com/photo-1527529482837-4698179dc6ce?auto=format&fit=crop&w=2200&q=90",desc:"A contemporary cultural gathering bringing people together through sound, food, art and shared experience."}
};
export default async function EventPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const event=data[slug];if(!event)notFound();return <main className="event-detail"><header className="nav overlay"><Link href="/" className="brand"><span className="brand-mark">J</span><span>JALENE</span><small>EVENT</small></Link><Link href="/events" className="back-light"><ArrowLeft size={16}/> All events</Link></header><section className="event-detail-hero" style={{backgroundImage:`linear-gradient(180deg,rgba(8,8,8,.25),rgba(8,8,8,.72)),url(${event.image})`}}><div className="detail-hero-copy"><span className="event-category">{event.category}</span><h1>{event.title}</h1><div className="detail-meta"><span><CalendarDays size={17}/>{event.date}</span><span><MapPin size={17}/>{event.place}</span></div></div></section><section className="detail-body"><div><span className="section-kicker"><span>THE EXPERIENCE</span></span><h2>Designed to be<br/><em>remembered.</em></h2></div><div><p className="lead">{event.desc}</p><p>Event details will be published by Jalene as each experience is confirmed. This independent Next.js site keeps event content editable in code or through a future CMS without any dependency on a website builder.</p><a className="button button-dark" href="/#contact">Ask about this event <ArrowUpRight size={17}/></a></div></section></main>}
